version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'olol'
      MYSQL_ROOT_PASSWORD: 'COMPOSE_ROOT_PASSWORD'
      MYSQL_USER: 'COMPOSE_USER'
      MYSQL_PASSWORD: 'COMPOSE_PASSWORD'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 1s
      retries: 5

  spring:
    container_name: spring-boot-ol-ol
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/olol
      spring.datasource.username: COMPOSE_USER
      spring.datasource.password: COMPOSE_PASSWORD
    volumes:
      - spring_data:/spring/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  my-db:
    driver: local
  spring_data: